# Generated by Django 5.2.4 on 2025-09-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=20, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.dayofweek', verbose_name='День недели')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='groups.group', verbose_name='Группа')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.timeslot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Расписание группы',
                'verbose_name_plural': 'Расписания групп',
                'ordering': ['day_of_week__order', 'time_slot__start_time'],
                'unique_together': {('group', 'day_of_week', 'time_slot')},
            },
        ),
    ]
